project_management_theseus/chat/urls.py
from django.urls import path
from . import views

app_name = 'chat'
urlpatterns = [
   
    path('', views.index, name='index'),
    path('create-direct/', views.create_direct_chat, name='create_direct'),  
    path('room/<int:room_id>/', views.room_view, name='room'),
    path('search/', views.search_chats, name='chat_search'),
    path('<int:room_id>/messages/', views.chat_messages, name='chat_messages'),
    path('<int:room_id>/send/', views.send_message, name='send_message'),
]

project_management_theseus/main/urls.py
from django.urls import path
from .views import index

urlpatterns = [
    path('', index, name='index'),
]

project_management_theseus/project_management_theseus/urls.py
from django.contrib import admin
from django.urls import path, include
from projects import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')), 
    path('projects/', include('projects.urls')),
    path('', include('main.urls')),
    path('tasks/<int:task_id>/update_status/', views.update_task_status_ajax),
    path('chat/', include('chat.urls', namespace='chat')),
]

project_management_theseus/main/models.py
from django.db import models

# Create your models here.

project_management_theseus/main/views.py
from django.shortcuts import render
from projects.models import Project, Task

def index(request):
    search_query = request.GET.get('q', '')

    projects = Project.objects.all()
    tasks = Task.objects.all()

    if search_query:
        projects = projects.filter(title__icontains=search_query)
        tasks = tasks.filter(title__icontains=search_query)

    context = {
        'projects': projects,
        'tasks': tasks,
        'search_query': search_query
    }
    return render(request, 'main/index.html', context)

project_management_theseus/main/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Проектное управление</title>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <!-- CSS Bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <!-- JS Bootstrap -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    {% load static %}
    {% load chat_tags %}
</head>
<body>
    <nav class="navbar">
        <a href="/" class="logo">
            <img src="{% static 'img/logo.png' %}" alt="Логотип">
        </a>
        {% if user.is_authenticated %}
            <a href="/" ><i class="fa-solid fa-list-check"></i>Мои проекты</a>
            {% if user.role != 'employee' %}
                <a href="{% url 'employee_list' %}" ><i class="fa-solid fa-users"></i>Сотрудники</a>
            {% endif %}
            <a  href="{% url 'chat:index' %}"><i class="fa-solid fa-message"></i>Сообщения</a>
            
            
            <form action="{% url 'logout' %}" method="post" style="display:inline;">
                {% csrf_token %}
                <button type="submit" class="nav-link"><i class="fa-solid fa-right-to-bracket"></i>Выйти</button>
            </form>
        {% else %}
            <a href="/users/login/"><i class="fa-solid fa-right-to-bracket"></i>Войти</a>
        {% endif %}
    </nav>

    <div class="container">
        {% block content %}{% endblock %}
    </div>

    <script>
        // Активация выпадающего меню
        document.addEventListener('DOMContentLoaded', function() {
            var dropdownElements = document.querySelectorAll('.dropdown-toggle');
            dropdownElements.forEach(function(el) {
                el.addEventListener('click', function(e) {
                    e.preventDefault();
                    var menu = this.nextElementSibling;
                    menu.style.display = menu.style.display === 'block' ? 'none' : 'block';
                });
            });
        });
    </script>
</body>
</html>